// Code generated by github.com/averak/protobq/cmd/protoc-gen-protobq. DO NOT EDIT.
// source: example/example.proto

package example

import (
	protobq "github.com/averak/protobq"
	protobq1 "github.com/averak/protobq/internal/protobuf/protobq"
	proto "google.golang.org/protobuf/proto"
	time "time"
)

var _ protobq.MaterializedView = (*Example)(nil)

func (mv *Example) Options() protobq.MaterializedViewOptions {
	ext, _ := proto.GetExtension(mv.ProtoReflect().Descriptor().Options(), protobq1.E_MaterializedView).(*protobq1.MaterializedView)
	return protobq.MaterializedViewOptions{
		EnableRefresh:   ext.GetEnableRefresh(),
		RefreshInterval: time.Duration(ext.GetRefreshIntervalMinutes()) * time.Minute,
	}
}
